"""empty message

Revision ID: 714c9c3343ac
Revises: 
Create Date: 2022-05-28 19:15:02.189827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714c9c3343ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_table', sa.Column('name', sa.String(), nullable=False))
    op.add_column('image_table', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'image_table', ['name'])
    op.drop_column('image_table', 'pixel_factor')
    op.drop_column('image_table', 'img_name')
    op.add_column('player__history', sa.Column('date_submitted', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player__history', 'date_submitted')
    op.add_column('image_table', sa.Column('img_name', sa.VARCHAR(), nullable=False))
    op.add_column('image_table', sa.Column('pixel_factor', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'image_table', type_='unique')
    op.drop_column('image_table', 'date')
    op.drop_column('image_table', 'name')
    # ### end Alembic commands ###
